Userのレポの実装
hackathon-21winter-05/HiQidas pull request #45
Opened 2021-12-06 17:03 UTC by xxarupakaxx

close : #44 

与えられたUserのインターフェイスの実装をした

主な変更点
- errors.goにerrorを追加
- database/user.goにメソッドを実装

2021-12-06 18:12 UTC, logica0419 reviewed
う～ん全体的な実装の方向として、最終的にひとつの「repository」というインターフェースに 全てのDBメソッドを定義して、それを一つの構造体で実装したいんだよね。その構造体作ってインターフェースとして返せば、インターフェースが簡単に実装できるじゃない
「ルーターインターフェースかます？」とか言ってた俺が言える口ではないが、リポジトリ内に無駄なインターフェースや構造体を作ってややこしくしたくないんだな
なので、databaseパッケージではなく、repositoryパッケージの方にDB構造体やgetDBメソッドをプライベートスコープで配置して、DB構造体に対してすべてのrepositoryのメソッドを付けていくという形の実装が一番きれいになると思うんだよね
User構造体とかは作っても最終的に一つの構造体に埋め込まなきゃいけなくなるので面倒くさくなるだけだと思う
参考: https://github.com/traPtitech/traQ/tree/master/repository

2021-12-06 18:12 UTC, logica0419 commented on repository/database/errors.go
> +	ErrNoRecordUpdated = errors.New("no Record Updated")
日本語と英語の齟齬あるので、レコードが無かっただったら「no record to delete」の方がよさそう
あと後ろの単語大文字にするの個人的に違和感あるんだけど俺だけかな

2021-12-06 20:25 UTC, logica0419 commented
後トランザクションに関して、なんか使いこなせてない感が否めない
多分もっと簡単でいいと思うんだよ…多分…
僕の考えとしてはここまでクリーンアーキテクチャにしっかり従わなければいけないとは思わないんだよね… 普通にrepository層でトランザクション作ってロールバック処理まで実装しちゃっていいと思ってる
理解せずに形だけの実装(何も理解してない)よりは、自分たちがきちんと理解できる範囲で実装するのがいいと思います
正直コピペ実装も悪くないんだけど、きちんと理解しながら実装するのが身のためだよな～と思う

とりあえずトランザクションとコンテクストについて僕が勉強しておきます
夜かどっかで方針を話し合おう

2021-12-07 02:58 UTC, xxarupakaxx commented
transaction、DBに保存するとき（service層）でやる予定だった

2021-12-07 03:08 UTC, logica0419 commented
今メチャクチャ技術系ブログの記事読んでた
service層でやるのでOK、俺も同意
ただ実装はもうちょっとうまくやれそうな気がする、ちょっと今調べてわかったこと、大きな流れをMDにまとめてみるね(多分実装よりも先に大まかな流れの理解をした方がいいと思う)

2021-12-07 16:17 UTC, xxarupakaxx commented
:kan:

2021-12-07 16:40 UTC, logica0419 requested changes
全体的に:yosa:
後は細かいとこ

2021-12-07 16:40 UTC, logica0419 commented on repository/repository_impl.go
> +	db, err := NewDBConnect(c)
ここエラーハンドリングしよう
エラーがnilじゃなかったらGormRepositoryはnilを返したい

2021-12-07 16:40 UTC, logica0419 commented on repository/repository_impl.go
> +func NewGormRepository(c config.Config) (*GormRepository, error) {
これは*GormRepositoryではなくRepositoryとして返してあげて
そうでないとそれ以外のところでインターフェースとして扱えなくなっちゃう
あとconfig.Configはポインタ(*config,Config)で渡す予定なのでそれにしといて

2021-12-07 16:40 UTC, logica0419 commented on repository/repository_impl.go
> +func NewDBConnect(c config.Config) (*gorm.DB, error) {
config.Configはポインタ(*config,Config)で渡す

2021-12-07 16:40 UTC, logica0419 commented on repository/transaction.go
> +type TransactionRepository interface {
Transaction単体でよさそう

2021-12-07 16:40 UTC, logica0419 commented on repository/transaction_impl.go
> +)
ここtxKey stringでそのまま定義して良くない？になっちゃった

2021-12-07 16:40 UTC, logica0419 commented on repository/user_impl.go
> +}
すまん、ここUser取得じゃなくてUsersID(ID配列)を取得だったわ(エンドポイント考えて)
[]uuid.UUIDを返すようインターフェース定義もついでに変えといてくれると助かる
名前はGetUsersIDがいいかな

2021-12-07 16:40 UTC, logica0419 commented on repository/repository.go
> +	TransactionRepository
Transactionは他と違ってテーブル操作をしないから、Repositoryという名前にしたくない
Transaction単体でよさそう
後特別なので先頭に持ってきといてほしい(わかりやすくするため)

2021-12-07 16:54 UTC, xxarupakaxx commented on repository/repository_impl.go
> +	db, err := NewDBConnect(c)
:tashikani:

2021-12-07 16:55 UTC, xxarupakaxx commented on repository/repository_impl.go
> +func NewGormRepository(c config.Config) (*GormRepository, error) {
忘れたありがとう

2021-12-07 17:03 UTC, xxarupakaxx commented
:kan:

2021-12-07 17:08 UTC, logica0419 approved these changes
完璧
TY

2021-12-07 17:08 UTC, merged