Historyのレポの実装
hackathon-21winter-05/HiQidas pull request #62
Opened 2021-12-08 17:06 UTC by xxarupakaxx

close : #52 

主な変更点
- GormRepositoryのメソッドとなるようなヒストリーのインターフェイスを実装した
- DeleteHistoryでheyaIDのみ使わなかったので、引数をheyaIDに変更した

2021-12-08 18:34 UTC, logica0419 requested changes

2021-12-08 18:34 UTC, logica0419 commented on repository/history_impl.go
> +func (repo *GormRepository) DeleteHistory(ctx context.Context, heyaID uuid.UUID) error {
いい忘れていたがこれ一応ByHeyaID付けといてほしいな、何が基準かわからなくなると困る

2021-12-08 18:36 UTC, xxarupakaxx commented on repository/history_impl.go
> +func (repo *GormRepository) DeleteHistory(ctx context.Context, heyaID uuid.UUID) error {
:kan::sleep:

2021-12-08 18:37 UTC, logica0419 commented
Userの時の実装にはDelete、UpdateにByIDついてたのにTsunaの時にはついてなかったの今更気づいた
どっちかに統一したいな～という思い
個人的にはByIDの方が明示的で良いと思う

2021-12-09 02:05 UTC, xxarupakaxx commented
全部詳しくByIDつけちゃいます

2021-12-09 03:50 UTC, logica0419 approved these changes
OK！

2021-12-09 03:51 UTC, merged