Heyaのレポの実装
hackathon-21winter-05/HiQidas pull request #65
Opened 2021-12-08 18:14 UTC by xxarupakaxx

close : #48 

- gormRepositoryのメソッドとしてheyaのインターフェイスの実装
- CreateHeyaの引数の変更

2021-12-08 18:48 UTC, logica0419 reviewed
ByIDの有り無し統一できたらPerfect

2021-12-08 18:58 UTC, logica0419 reviewed
ByIDの有り無し統一できたらPerfect

2021-12-08 18:58 UTC, logica0419 commented on repository/heya_impl.go
> +	}
NULLABLEのやつがnil入ったマップ受け取るとNULLになる可能性があるで、念のため全カラム面倒だとは思うがifでValidationしてnilじゃなかったら値を入れるという形にしてほしい

2021-12-09 02:15 UTC, xxarupakaxx commented on repository/heya_impl.go
> +	}
てかheya全部not nullだったので https://github.com/hackathon-21winter-05/HiQidas/issues/64　をやってPUSHする

2021-12-09 02:17 UTC, xxarupakaxx commented on repository/heya_impl.go
> +	}
いやerrors.goにErrNillUUIDなのを追加してやりたいからほかのすべてのレポＰＲがマージされたら一気にやりますのでByIDだけ修正する

2021-12-09 03:49 UTC, logica0419 requested changes

2021-12-09 03:49 UTC, logica0419 commented on repository/heya_impl.go
> +	result := db.Model(&model.Heya{}).
これはマップのままでよかった
「ゼロ値」にはnilの他に""や0やfalseも含まれるから、nilだけValidationが欲しいという感じ
今のやつだとnilじゃないゼロ値の時更新されないよね

2021-12-09 03:49 UTC, logica0419 commented on repository/heya_impl.go
> +func (repo *GormRepository) UpdateHeya(ctx context.Context, heya *model.Heya) error {
ByID

2021-12-09 03:49 UTC, logica0419 commented on repository/heya.go
>  	UpdateHeya(ctx context.Context, heya *model.Heya) error
ByID

2021-12-09 03:56 UTC, xxarupakaxx commented on repository/heya_impl.go
> +	result := db.Model(&model.Heya{}).
ありがとう
:kan:

2021-12-09 05:44 UTC, logica0419 approved these changes
Update以外はOK

2021-12-09 05:44 UTC, merged