dbのモデルを書いた
hackathon-21winter-05/HiQidas pull request #7
Opened 2021-12-04 04:26 UTC by xxarupakaxx

ref: #1 

- heya user hisory image tuna hiqidashiの構造体を書いた
- ドキュメントの修正

2021-12-04 05:48 UTC, logica0419 requested changes
まだ細かいところ見る余裕無いけど一旦根本の気になったところを

2021-12-04 05:48 UTC, logica0419 commented on docs/db_schema.md
> +## Heya
小文字

2021-12-04 05:48 UTC, logica0419 commented on docs/db_schema.md
>  シート(仮称)情報
名前直しといて欲しい

2021-12-04 05:48 UTC, logica0419 commented on docs/db_schema.md
> +|  deleted_at   | datetime |   true   |     |                   |        |        シートの削除日時        |
issueでも言ったけどいるか検討
後名前ヘヤに直しといて欲しい

2021-12-04 05:48 UTC, logica0419 commented on docs/db_schema.md
> +|  deleted_at   | datetime |   true   |     |                   |        |        シートの削除日時        |
検討
名前はHiqidashiで

2021-12-04 05:48 UTC, logica0419 commented on docs/db_schema.md
>  ヒキダシ同士のコネクション情報
名前直しといて

2021-12-04 06:27 UTC, logica0419 commented
Tuna、Tsunaの方が混乱を産まなくて良いかも(Tunaはマグロだった気がする)

2021-12-04 07:04 UTC, xxarupakaxx commented
:tashikani:
変えておきます

2021-12-04 11:16 UTC, logica0419 requested changes
気づいた点書いときました

2021-12-04 11:16 UTC, logica0419 commented on go.mod
> +	github.com/gofrs/uuid v4.2.0+incompatible // indirect
すごい偏見かもしれんが、[こっち](https://github.com/google/uuid)の方が公式感強い気がするのと安心感があるので使うならこっちにして欲しいなー

2021-12-04 11:16 UTC, logica0419 commented on model/hiqidashi.go
> +	ParentID       uuid.NullUUID  `json:"parent_id"      gorm:"type:char(36);not null"`
型がNullableなのにGorm定義not nullになってない？:w:他にもやってそうだからちょっと探してみて欲しい

2021-12-04 11:25 UTC, xxarupakaxx commented on go.mod
> +	github.com/gofrs/uuid v4.2.0+incompatible // indirect
そっちの更新が1年以上前だったからなんか使うのやめたんだよね

2021-12-04 14:28 UTC, logica0419 commented on go.mod
> +	github.com/gofrs/uuid v4.2.0+incompatible // indirect
あ～なるほど、そういう事情があったのか
じゃあそのままでいいや、ごめん

2021-12-04 16:36 UTC, xxarupakaxx commented on model/hiqidashi.go
> +	ParentID       uuid.NullUUID  `json:"parent_id"      gorm:"type:char(36);not null"`
これに関しては:gomen:
今直そうと思ったんだけどlastEditorIDのところ、CreatorIDが作成した時点でその人がLastEditorIDだしnot nullにしてもいいんじゃない？って思った

2021-12-04 17:13 UTC, logica0419 commented on model/hiqidashi.go
> +	ParentID       uuid.NullUUID  `json:"parent_id"      gorm:"type:char(36);not null"`
あ、確かに :kashikoi:
NULL例外処理めんどくさいしそれでいいや

2021-12-04 20:05 UTC, logica0419 commented
今更気づいたがforeign keyの設定間違ってない？
多分今`foreignKey:ID`のとこ、`references:ID`だと思うんだわ
https://gorm.io/ja_JP/docs/belongs_to.html

2021-12-04 22:29 UTC, logica0419 commented on model/histories.go
> +}
ここ、primarykeyのpriority明記しといて上げると親切かも
https://gorm.io/ja_JP/docs/indexes.html#%E3%83%95%E3%82%A3%E3%83%BC%E3%83%AB%E3%83%89%E3%81%AE%E5%84%AA%E5%85%88%E5%BA%A6

2021-12-04 22:30 UTC, logica0419 commented
フォーリンキーに関するアソシエーションのとこ、勉強してからも一回チェックする

2021-12-05 02:02 UTC, xxarupakaxx commented on model/histories.go
> +}
:kan:

2021-12-05 10:05 UTC, logica0419 commented
フォーリンキーのアソシエーションについて
https://gorm.io/ja_JP/docs/associations.html
どうやらよくよく調べてみたら複数のテーブルを一気に更新できたり一気に削除できたり一気に取って来れたりする機能だということがわかった
僕の書いてた「foreign」は外部キー制約のことで、これはmigration時に作るものだったのでこっちのモデルではやらなくて良さそうなことがわかってしまった、すまん
ただ、HiqidashiとImageはBelong toの関係結んどいた方が取り回しやすいかもしれん
あとはUserとHeyaもかな…
基本全てのテーブル、IDがUUIDなので変更の必要がない = 外部キーで繋がったIDを同時に変更することがない ので、同時生成・同時削除のどちらかを使うとしたら上の二組かなーと思った

2021-12-05 18:27 UTC, logica0419 requested changes

2021-12-05 18:27 UTC, logica0419 commented on model/hiqidashi.go
> +	ColorID        int           `json:"color_id"       gorm:"type:int(11);not null"`
tinyint unsignedのほうが良さそう
表示幅も1にしといてほしい

2021-12-05 18:27 UTC, logica0419 commented on model/heya.go
> +	LastEditorUser *User     `json:"-"              gorm:"foreignKey:ID"`
ここのアソシエーションはいらなそう

2021-12-05 18:27 UTC, logica0419 commented on model/hiqidashi.go
> +	LastEditorUser *User         `json:"-"              gorm:"foreignKey:ID"`
ここのアソシエーションはいらなそう

2021-12-05 18:27 UTC, logica0419 commented on model/hiqidashi.go
> +	Heya           *Heya         `json:"-"              gorm:"foreignKey:ID"`
ここのアソシエーションはいらなそう

2021-12-05 18:27 UTC, logica0419 commented on model/hiqidashi.go
> +	ImageID        uuid.UUID     `json:"image_id"       gorm:"type:char(36)"`
hiqidashi "HAS ONE" imageのアソシエーションにするならいらないと思う
https://gorm.io/ja_JP/docs/has_one.html

2021-12-05 18:27 UTC, logica0419 commented on model/histories.go
> +	SheetID uuid.UUID `json:"sheet_id" gorm:"type:char(36);not null;primaryKey;index:idx_history_user_id,priority:2"`
ここHeyaに直し忘れてる？

2021-12-05 18:27 UTC, logica0419 commented on model/hiqidashi.go
> +	LastEditorID   uuid.NullUUID `json:"last_editor_id" gorm:"type:char(36);not null"`
ここ、型をUUIDにした方が良い

2021-12-05 18:27 UTC, logica0419 commented on model/hiqidashi.go
> +	Description    string        `json:"description"    gorm:"type:text"`
NullableならNullString(sqlってパッケージ)

2021-12-05 18:27 UTC, logica0419 commented on model/heya.go
> +	Description    string    `json:"description"    gorm:"type:text"`
NullableならNullString(sqlってパッケージ)

2021-12-05 18:27 UTC, logica0419 commented on model/heya.go
> +	Deleted        bool      `json:"deleted"        gorm:"type:boolean;default:false"`
not null入れとこうぜ

2021-12-05 18:27 UTC, logica0419 commented on model/hiqidashi.go
> +	HeyaID         uuid.UUID     `json:"heya_id"        gorm:"type:char(36);not null"`
index付けといてほしい

2021-12-05 18:27 UTC, logica0419 commented on model/hiqidashi.go
> +	CreatorID      uuid.UUID     `json:"creator_id"     gorm:"type:char(36);not null"`
index付けといてほしい

2021-12-05 18:27 UTC, logica0419 commented on model/tsuna.go
> +	Hiqidashis   []Hiqidashi `json:"-"             gorm:"foreignKey:ID"`
ここのアソシエーションはいらなそう

2021-12-05 18:27 UTC, logica0419 commented on model/hiqidashi.go
> +	Image          *Image        `json:"-"              gorm:"foreignKey:ID"`
多分ポインタの必要ない感じがする

2021-12-05 18:27 UTC, logica0419 commented on model/images.go
> +type Image struct {
これは一応「画像」ではなく「お絵描き」の方だと思うので、混乱を避けるために「Drawing」とかにしよう

2021-12-05 18:27 UTC, logica0419 commented on model/images.go
> +	Image []byte    `json:"image" gorm:"type:MEDIUMBLOB;not null"`
SVGで来るのかは分かんないけどとりあえずstring型にするか

2021-12-05 18:27 UTC, logica0419 commented
細かいところまで全部見ました

2021-12-06 02:59 UTC, xxarupakaxx commented
:kan:

2021-12-06 03:02 UTC, logica0419 commented
お疲れ！LGTM
いったんマージ

2021-12-06 03:02 UTC, logica0419 approved these changes

2021-12-06 03:02 UTC, merged