UsersのエンドポイントとHeyasの一部
hackathon-21winter-05/HiQidas pull request #9
Opened 2021-12-04 07:57 UTC by xxarupakaxx

Usersのエンドポイントを書きました
一部/heyaから欲しいものがあったエンドポイントがあったのでheyaもちょっと作った

2021-12-04 08:37 UTC, logica0419 requested changes
グループめいは基本sつける方針で行くという話をしてたと思うから、スキーマ名もその流れを踏襲して欲しい

2021-12-04 08:37 UTC, logica0419 commented on schema/pb/rest/heya.proto
> +// GET /heya/{heyaId}
グループはheyasで統一したい

2021-12-04 08:37 UTC, logica0419 commented on schema/pb/rest/user.proto
> +message GetUserResponse {
UsersUserIDResponceみたいな感じで、パラメーターまで含めて名前にしちゃってほしー

2021-12-04 08:39 UTC, logica0419 commented
あ、あと多分protobuf以外にスキーマ定義必要なのないから、リポジトリ直下に`/protobuf`ってフォルダ作ってそこに移動させて欲しい

2021-12-04 09:47 UTC, xxarupakaxx commented
:kan:

2021-12-04 10:57 UTC, logica0419 commented
スキーマ名の方、レビューコメントに書いたようにパラメーターまで全てを繋げて欲しい
GetHeyaIDResponse -> GetHeyasHeyaIDReaponseみたいな感じ
APIのエンドポイントから直感でスキーマ名を打てるよう、統一しておきたいんだな

2021-12-04 11:07 UTC, logica0419 requested changes
とりあえずメモの意味も兼ねて全部書いた、みみっちいことしてすまん
PUTのスキーマはちょっと後で考える
HeyaIDsっていうmessage作っちゃっていい感じするな

2021-12-04 11:07 UTC, logica0419 commented on protobuf/rest/heyas.proto
> +message GetHeyasResponse {
ここIDの配列返したい気持ちある
リストはIDで、要素ごとの情報が欲しいならそれぞれのIDのAPIを叩いてもらうことで、エンドポイントの意味をきちんと分割して正規化(と言って良いのかわからんが)をしたい

2021-12-04 11:07 UTC, logica0419 commented on protobuf/rest/heyas.proto
> +message GetHeyaIdResponse {
名前の統一お願い

2021-12-04 11:07 UTC, logica0419 commented on protobuf/rest/users.proto
> +message GetUserResponse {
名前の統一お願い

2021-12-04 11:07 UTC, logica0419 commented on protobuf/rest/users.proto
> +message GetUsersResponse {
ここもID配列がいい

2021-12-04 11:07 UTC, logica0419 commented on protobuf/rest/users.proto
> +message PatchUserRequest {
名前の統一お願い
後ここはPatchがProto的には正しいのかもしれないが、RESTのエンドポイントから直感的にスキーマ名を出したいのでPutのままがいいなぁ

2021-12-04 11:07 UTC, logica0419 commented on protobuf/rest/users.proto
> +message GetUserMeResponse {
名前の統一お願い

2021-12-04 11:07 UTC, logica0419 commented on protobuf/rest/users.proto
> +message PatchUserMeRequest {
名前の統一とPutお願い

2021-12-04 11:07 UTC, logica0419 commented on protobuf/rest/users.proto
> +message GetUserMeIconResponse {
ここはファイル直接返しちゃう予定なので今のところいらないや、ごめんね

2021-12-04 11:07 UTC, logica0419 commented on protobuf/rest/users.proto
> +message GetUserMeHyasResponse {
名前の統一お願い
あとここもid一覧返したい

2021-12-04 11:28 UTC, xxarupakaxx commented on protobuf/rest/users.proto
> +message PatchUserRequest {
PutよりEditでいいですか(PutよりもEditのほうが気分がいい)

2021-12-04 11:36 UTC, xxarupakaxx commented
:kan:

2021-12-04 14:51 UTC, logica0419 requested changes
Editにしたいモチベがわからずになってるのでちょっと詳しく教えてほしいわ

2021-12-04 14:51 UTC, logica0419 commented on protobuf/rest/heyas.proto
> +message PostHeyasResponse {
ここは生成されたヘヤを返したい

2021-12-04 14:51 UTC, logica0419 commented on protobuf/rest/users.proto
> +    repeated string favorite_hiqidashi_id = 2;
これ別のエンドポイントで返そう、あとで書き足す

2021-12-04 14:51 UTC, logica0419 commented on protobuf/rest/users.proto
> +message EditUsersMeRequest {
nameをPUTしておいてくれればいいかな

2021-12-04 14:51 UTC, logica0419 commented on protobuf/rest/users.proto
> +message GetUserdMeHeyasResponse {
Typo
あとこれはエンドポイント名再考したいな
heyasだと抽象的すぎる

2021-12-04 14:51 UTC, logica0419 commented on protobuf/rest/heyas.proto
> +message Status {
これ汎用性高そうだからCommonとかで括り出してえ

2021-12-04 16:24 UTC, xxarupakaxx commented
Editのほうが変更してる感が自分の中で強いからかなぁ

2021-12-04 19:04 UTC, logica0419 commented
う～んエンドポイント見て直感で書きにくいのだけが難点なんだよな… クライアント側から書いてるときに「なんでPUTで通らないの？？？？」みたいな苦情が飛んできそう
まあでもいいや、それの方がいいという強い希望があればEDITで通してもらっても構わん、任せる

2021-12-04 19:17 UTC, logica0419 commented on protobuf/rest/users.proto
> +    string icon_file_id = 3;
レスポンスのためのUserストラクトにfile_idいらないや、UserIDだけでアイコン取得できるようにするわ

2021-12-05 05:18 UTC, xxarupakaxx commented
たしかにクライアントからみて直感的なのはPUTだしPUTに変えます

2021-12-05 06:17 UTC, logica0419 reviewed
ありがとう〜
人間は愚かなので共同開発時はこういう「ひねらない」って結構大事だと思ってる
あと、protobufの立ち位置を考えて、今回のパッケージを`model/pb`から`server/pb`に変更したいのでそこをよろしく

2021-12-05 06:17 UTC, logica0419 commented on protobuf/rest/heyas.proto
> +    Heyas heyas = 1;
生成されたヘヤ一つだから多分ここheya

2021-12-05 06:22 UTC, xxarupakaxx commented on protobuf/rest/heyas.proto
> +    Heyas heyas = 1;
そうだったありがとう:kansya:

2021-12-05 06:25 UTC, logica0419 requested changes
ありがとう〜
人間は愚かなので共同開発時はこういう「ひねらない」って結構大事だと思ってる
あと、protobufの立ち位置を考えて、今回のパッケージを`model/pb`から`server/pb`に変更したいのでそこをよろしく

2021-12-05 06:25 UTC, logica0419 commented on protobuf/rest/users.proto
> +message PutUsersUserIdRequest {
とりあえずNameの変更だけ実装しとこう

2021-12-05 06:25 UTC, logica0419 commented on protobuf/rest/users.proto
> +    repeated string favorite_heya_id = 2;
これも別で返そうかと思う

2021-12-05 06:25 UTC, logica0419 commented on protobuf/rest/users.proto
> +message PutUsersMeRequest {
ここも名前だけ

2021-12-05 08:30 UTC, xxarupakaxx commented on protobuf/rest/users.proto
> +    repeated string favorite_heya_id = 2;
自分がfavoirteしたヘヤを別のエンドポイント(例えば、/users/me/faivorites)で返すってことであってる？

2021-12-05 08:34 UTC, xxarupakaxx commented
～～/hiqidashi情報を書いた

2021-12-05 08:43 UTC, xxarupakaxx commented
hiqidahiのPUT,Deleteのエンドポイント、
`/heyas/{heyaId}/hiqidashi/{hiqidashiId}` だと長いし悩み

2021-12-05 09:32 UTC, logica0419 commented
Hiqidashi関係は、画像以外基本WebSocketでやり取りを済ませようと思っている

2021-12-05 09:34 UTC, logica0419 commented
あとHiqidashiをRESTで扱うとしたらhiqidashisってグループ作るよ

2021-12-05 09:37 UTC, xxarupakaxx commented
なるほど
じゃあ消しておきます:pray:

2021-12-05 09:55 UTC, logica0419 commented on protobuf/rest/heyas.proto
> +}
まあアーカイブにするかは別のところで話し合うところなので、エンドポイントはこれでOK

2021-12-05 09:55 UTC, logica0419 commented on protobuf/rest/users.proto
> +    repeated string favorite_heya_id = 2;
合ってる
僕がスッキリしたエンドポイント設計の方が好きな(複合的な意味を持つエンドポイントを作るのがあまり好きじゃない)ので、meに余計な情報をぶち込みたくないという思いがある
あくまで僕の好みなので違う考え方してたら言って欲しいなーって感じ

2021-12-05 09:56 UTC, logica0419 commented
とりあえずMDのエンドポイントの方更新しといたのでそれで進めてもらいたい
後そろそろ一旦マージしてルーターの大枠を決めたいな

2021-12-05 16:34 UTC, logica0419 requested changes

2021-12-05 16:34 UTC, logica0419 commented on protobuf/rest/heyas.proto
> +}
ここ削除で

2021-12-05 16:34 UTC, logica0419 commented on protobuf/rest/heyas.proto
> +    string updated_at = 7;
いったんこれ使ってやってみてくれ
https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#timestamp
これみたいな感じでimportできるはず、できなかったらその時考えよう
https://developers.google.com/protocol-buffers/docs/proto3#any

2021-12-05 16:34 UTC, logica0419 commented on protobuf/rest/hiqidashi.proto
> +}
これもいったん削除でいいかな

2021-12-05 16:34 UTC, logica0419 commented on protobuf/rest/users.proto
> +package Users;
パッケージ名の大文字小文字統一しよう

2021-12-05 17:01 UTC, xxarupakaxx commented on protobuf/rest/heyas.proto
> +    string updated_at = 7;
いったんこれみて書き直してビルドしたときに失敗したらそのときに....

2021-12-05 17:09 UTC, logica0419 commented on protobuf/rest/heyas.proto
> +    string updated_at = 7;
その方向で～

2021-12-05 17:15 UTC, xxarupakaxx commented
:kan:

2021-12-05 17:45 UTC, logica0419 requested changes

2021-12-05 17:45 UTC, logica0419 commented on protobuf/rest/heyas.proto
> +    google.protobuf.timestamp updated_at = 7;
手元で試したけどTimestampの頭文字大文字でパッケージ登録されてるから大文字にしないとダメだ
あと、Goに変換してみたらこのようなパッケージで生成されていることが分かった
https://pkg.go.dev/google.golang.org/protobuf/types/known/timestamppb
これ使えばserver層でパパっと変換して乗っけられるわ

ただクライアント側ちょっと大変になるかも(小声)

2021-12-06 02:21 UTC, xxarupakaxx commented on protobuf/rest/heyas.proto
> +    google.protobuf.timestamp updated_at = 7;
どっちにしよ

2021-12-06 02:27 UTC, logica0419 commented on protobuf/rest/heyas.proto
> +    google.protobuf.timestamp updated_at = 7;
JSのデフォルトオブジェクトであるDateとほぼ同じ仕様してるからいったんTimestamp使用してみよう
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Date

2021-12-06 02:38 UTC, logica0419 commented
あとはusersのPUTの2つだけやってくれたらマージします

2021-12-06 03:01 UTC, xxarupakaxx commented
:kan:

2021-12-06 03:03 UTC, logica0419 commented
お疲れ！LGTM
いったんマージ

2021-12-06 03:03 UTC, logica0419 approved these changes

2021-12-06 03:03 UTC, merged